### ISSUE TITLE
InMoov repo 1.0.0

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#143]
Ready to freeze it Inside the jar ?

**Comment by hairygael** [comment]
Freeze!
I haven't tested though since a few versions...
I hope you know what you are doing!
Ehehe!
Sounds like Christmas is pushing some Java stuff out there.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-12-22 15:40 GMT+01:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
Jar is now updated with an estimated stable inmoov repo ( we can still push urgent mods )

![image](https://user-images.githubusercontent.com/18124594/34315996-d5b2e832-e78b-11e7-9a36-6c318c80bca7.png)
