### ISSUE TITLE
Enter gestures keyword

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#60]
possible to override it ? to launch gestures without enter the magical keyword ?

**Comment by hairygael** [comment]
We can try, I'm worried that with English version chatbot, which is much more complex than the French chatbot, it might end up answering things to the voice commands instead of doing the requested gestures.

By the way, I tested the French chatbot and it doesn't work really well, it uses very often default response instead of using the possible AIML responses. Do you have the same?

**Comment by moz4r** [comment]
great ! will think to add an option , but not easy to tweak this part.
about french chatbot totaly agree it is unstable state , there is so much work to do , we are alone to feed it.
If you have some examples to push some updates...
My goal at the begining was to work on it , at the end I will return :)

**Comment by moz4r** [comment]
removed magical word , to test
