### ISSUE TITLE
Inmoov shutdown broken

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#97]
todo : use stopService() from java land

**Comment by supertick** [comment]
Runtime.shutdown(sec) not working ?

**Comment by moz4r** [comment]
Strange issues from python land. 
The solution to use service related stopService() is cleaner I think

**Comment by supertick** [comment]
Just to be clear ..
stopService stops the threads ...
releaseService calls stopService AND purges all scheduled tasks AND removes the service from the registry and publishes events saying the service has been released ..
So if you want to completely remove a service use releaseService

**Comment by moz4r** [comment]
Thank you for info ! I will use release when I want to shutdown . At this time I just put some things inside services shutdown routines related. Like writeAndQuit inside programab. Or rest()+disable inside Inmoov. Goal is to run some tasks when user use the swingui cross.

**Comment by hairygael** [comment]
Hello guys,
This is more a message for Anthony.
When InMoov is shutting down (inmoov-develop), it gets back to rest()
position, that is good and safe.
But after that, it doesn't disable() the servos before shutting down MRL
completely. (version MRL 1.0.2340)
So, we currently need to manually turn off the power to make sure the
servos stop buzzing.

Is it something fixed with more recent versions or does it still remain?

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-08-19 17:13 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
just tested the last build on whole robot, seem ok. for you too ?

**Comment by hairygael** [comment]
Hello Anthony,
I will not be able to test for a while. My third InMoov is now set on the
exhibition. My second InMoov is dismantled in suitcases ready to go to the
Makerfaire Eindhoven, and my first InMoov is out of the workshop for a show.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-08-27 19:37 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
aaarg master without InMoov :( 
You need a fourth inmoov !!!
Have fun for Makerfaire

**Comment by hairygael** [comment]
Thanks Anthony!


Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-08-28 22:15 GMT+02:00 Anthony <notifications@github.com>:

**Comment by supertick** [comment]
closing - Gael can re-open if noWorky for him ..
Thanks..

**Comment by hairygael** [comment]
Shutting down is fixed, very good!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-09-14 18:38 GMT+02:00 GroG <notifications@github.com>:
